// <auto-generated />
namespace CSU_CRM_WEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatedoscamposdabd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedoscamposdabd));
        
        string IMigrationMetadata.Id
        {
            get { return "201504132014081_update dos campos da bd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
