 INSERT INTO [dbo].[FormatosImportacao]([Formato],[Descricao],[TipoComprimento],[SeparadorDecimal],[SeparadorMilhares]) VALUES ('BCI','BCI',2,'.',',') 
 INSERT INTO [dbo].[FormatosImportacao]([Formato],[Descricao],[TipoComprimento],[SeparadorDecimal],[SeparadorMilhares]) VALUES ('BI2','BIM 2',2,'.',',') 
 INSERT INTO [dbo].[FormatosImportacao]([Formato],[Descricao],[TipoComprimento],[SeparadorDecimal],[SeparadorMilhares]) VALUES ('BIM','BIM',2,'.',',') 
 INSERT INTO [dbo].[FormatosImportacao]([Formato],[Descricao],[TipoComprimento],[SeparadorDecimal],[SeparadorMilhares]) VALUES ('SB','Standard Bank',1,',','.') 
 INSERT INTO [dbo].[FormatosImportacao]([Formato],[Descricao],[TipoComprimento],[SeparadorDecimal],[SeparadorMilhares]) VALUES ('STD','standard',1,',','.') 



 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'STD', 1,'NumeroConta',1, 2,2,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'STD', 5,'DataMovimento',7, 1,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'STD', 5,'Numero',8, 2,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'STD', 5,'DataValor',9, 4,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'STD', 5,'Obs',10, 5,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'STD', 5,'ValorMov',11, 6,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'STD', 1,'DataInicial',2, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'STD', 1,'DataFinal',3, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'STD', 1,'NumeroExtracto',4, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'STD', 1,'SaldoInicial',5, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'STD', 1,'SaldoFinal',6, 2,6,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BIM', 1,'NumeroConta',1, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BIM', 1,'DataInicial',2, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BIM', 1,'DataFinal',3, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BIM', 1,'NumeroExtracto',4, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BIM', 1,'SaldoInicial',5, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BIM', 1,'SaldoFinal',6, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BIM', 5,'DataMovimento',7, 1,0,'dd/MM/yyyy') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BIM', 5,'Numero',8, 5,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BIM', 5,'DataValor',9, 2,0,'dd/MM/yyyy') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BIM', 5,'Obs',10, 3,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BIM', 5,'ValorMov',11, 4,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BCI', 1,'NumeroConta',1, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BCI', 1,'DataInicial',2, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BCI', 1,'DataFinal',3, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BCI', 1,'NumeroExtracto',4, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BCI', 1,'SaldoInicial',5, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BCI', 1,'SaldoFinal',6, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BCI', 5,'DataMovimento',7, 8,0,'yyyyMMdd') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BCI', 5,'Numero',8, 10,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BCI', 5,'DataValor',9, 8,0,'yyyyMMdd') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BCI', 5,'Obs',10, 11,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BCI', 5,'ValorMov',11, 5,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BI2', 1,'NumeroConta',1, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BI2', 1,'DataInicial',2, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BI2', 1,'DataFinal',3, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BI2', 1,'NumeroExtracto',4, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BI2', 1,'SaldoInicial',5, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BI2', 1,'SaldoFinal',6, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BI2', 5,'DataMovimento',7, 1,0,'dd/MM/yyyy') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BI2', 5,'Numero',8, 8,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BI2', 5,'DataValor',9, 3,0,'dd/MM/yyyy') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BI2', 5,'Obs',10, 7,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'BI2', 5,'ValorMov',11, 4,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'SB', 5,'ValorMov',11, 6,0,'C') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'SB', 1,'DataInicial',1, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'SB', 1,'DataFinal',2, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'SB', 1,'NumeroExtracto',3, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'SB', 1,'SaldoInicial',4, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'SB', 1,'SaldoFinal',5, 0,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'SB', 5,'DataMovimento',6, 1,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'SB', 5,'Numero',7, 5,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'SB', 5,'DataValor',8, 2,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'SB', 5,'Obs',9, 3,0,'') 
 INSERT INTO [dbo].[LinhasFormatosImportacao]([IdLinha],[Formato],[TipoItem],[Campo],[Ordem],[Posicao],[Comprimento],[FormatoEspecial]) VALUES (NEWID(), 'SB', 5,'ValorMov',10, 4,0,'D') 
