//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSU_CRM_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Empresas
    {
        public string Codigo { get; set; }
        public string IDNome { get; set; }
        public string IDMorada { get; set; }
        public string Categoria { get; set; }
        public string IDTelefone { get; set; }
        public string IDIndicativoTelefone { get; set; }
        public string IDEmail { get; set; }
        public string IDLocalidade { get; set; }
        public string IFNIF { get; set; }
    }
}
