//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSU_CRM_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Bancos_Cobrancas
    {
        public Nullable<short> tipoconta { get; set; }
        public string Banco { get; set; }
        public string Descricao { get; set; }
        public string numconta { get; set; }
        public string nib { get; set; }
        public string IBAN { get; set; }
        public string SWIFT { get; set; }
        public string Moeda { get; set; }
    }
}
