//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSU_CRM_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Pendentes_Doc_Clientes
    {
        public string Modulo { get; set; }
        public string TipoEntidade { get; set; }
        public string Entidade { get; set; }
        public string TipoDoc { get; set; }
        public string NumDoc { get; set; }
        public int NumDocInt { get; set; }
        public Nullable<System.DateTime> DataDoc { get; set; }
        public Nullable<System.DateTime> DataVenc { get; set; }
        public Nullable<double> ValorTotal { get; set; }
        public Nullable<double> ValorPendente { get; set; }
        public string Moeda { get; set; }
        public Nullable<double> Cambio { get; set; }
        public Nullable<short> NumAvisos { get; set; }
        public short NumPrestacao { get; set; }
        public string Serie { get; set; }
        public string Conta { get; set; }
    }
}
